[Console]::OutputEncoding = [Text.Encoding]::UTF8
$adb = 'D:\DevData\Android\Sdk\platform-tools\adb.exe'
Write-Output '=== try curl ==='
& $adb shell 'curl -sS -m 20 "https://lrclib.net/api/search?track_name=So%20Long%2C%20London&artist_name=Taylor%20Swift" -H "User-Agent: LyricCaptioner/0.1.0" | head -c 600'
Write-Output ''
Write-Output '=== try toybox wget ==='
& $adb shell 'toybox wget -q -O - "https://lrclib.net/api/search?track_name=So%20Long%2C%20London&artist_name=Taylor%20Swift" | head -c 600'
Write-Output ''
Write-Output '=== ping deepseek ==='
& $adb shell 'curl -sS -m 10 -o /dev/null -w "%{http_code}" https://api.deepseek.com/chat/completions'
